import { createContext, useContext, useState } from "react";

const LanguageContext = createContext({ language: "English (UK)", setLanguage: () => {} });

const translations = {
  "English (UK)": {
    // Navigation
    command: "Command",
    communications: "Communications",
    organization: "Organization",
    workspace: "Workspace",
    dashboard: "Dashboard",
    ceo: "CEO Messages",
    announcements: "Announcements",
    notices: "Notices",
    news: "News",
    employees: "Employees",
    departments: "Departments",
    meetings: "Meeting Platform",
    settings: "Settings",
    safety: "Safety",
    leave: "Leave",
    feedback: "Feedback",
    calendar: "Calendar",
    
    // Common
    searchPlaceholder: "Search people, docs, projects…",
    notifications: "Notifications",
    signOut: "Sign Out",
    welcome: "Welcome",
    logout: "Logout",
    pinnedAddress: "Pinned address",
    
    // Settings
    appearance: "Appearance",
    language: "Language & region",
    darkMode: "Deep obsidian, ambient background",
    lightMode: "Brushed titanium, daylight palette",
    interfaceLanguage: "Interface language set to",
    timezone: "Time zone follows your campus: Europe/London (BST).",
    companyAnnouncements: "Company announcements",
    companyAnnouncementsHint: "Critical broadcasts always deliver.",
    meetingReminders: "Meeting reminders",
    meetingRemindersHint: "10 minutes before start.",
    leaveDecisions: "Leave decisions",
    weeklyDigest: "Weekly digest",
    reduceMotion: "Reduce motion",
    reduceMotionHint: "Disables parallax and ambient motion.",
    highContrast: "High contrast",
    largerText: "Larger text",
    accessibility: "Accessibility",
    crewPreferences: "Team preferences",
    settingsDescription: "Theme, language, notifications, accessibility, profile and security controls.",
    profile: "Profile",
    security: "Security",
    displayName: "Display name",
    workEmail: "Work email",
    desk: "Desk",
    deskLocation: "Novaterra · Remote",
    digitalCampusCredential: "Digital campus credential",
    digitalCampusCredentialStatus: "Provisioned · expires 2027",
    twoFactorAuthentication: "Two-factor authentication",
    twoFactorAuthenticationStatus: "Hardware key · active",
    activeSessions: "Active sessions",
    activeSessionsStatus: "3 devices",
    cameraOff: "Camera off",
    toggleMic: "Toggle mic",
    toggleCamera: "Toggle camera",
    backgroundBlur: "Background blur",
    micOffMessage: "Microphone muted",
    micOnMessage: "Microphone unmuted",
    cameraOffMessage: "Camera turned off",
    cameraOnMessage: "Camera turned on",
    joinedMeeting: "Joined Q3 Company All-Hands",
    enterMeetingRoom: "Enter meeting room",
    meetingPlatform: "Meeting platform",
    missionControlLobby: "Collaboration Hub",
    meetingLobbyDescription: "Check your devices, then enter the room. Rooms are ephemeral and encrypted end to end.",
    endToEndEncrypted: "End-to-end encrypted",
    autoTranscriptionOn: "Auto-transcription on",
    latency: "Latency 18 ms",
    todayRooms: "Today's meetings",
    liveSession: "Live · Q3 Company All-Hands",
    missionControl: "Collaboration Hub",
    chat: "Chat",
    people: "People",
    board: "Board",
    notes: "Notes",
    shareScreen: "Share screen",
    screenShareStopped: "Screen share stopped",
    screenShareStarted: "Screen share started",
    raiseHand: "Raise hand",
    handRaised: "Hand raised",
    handLowered: "Hand lowered",
    record: "Record",
    leftMeeting: "You left the meeting",
    sendMessage: "Send message",
    signIn: "Sign In",
    welcomeBack: "Welcome back",
    enterCredentials: "Enter your credentials to access the company workspace",
    email: "Email",
    emailPlaceholder: "name@novaterra.io",
    password: "Password",
    passwordPlaceholder: "••••••••",
    authenticating: "Authenticating…",
    demoLoginHelp: "Demo: Use any email and password (6+ chars)",
    saveProfile: "Save profile",
    profileUpdated: "Profile updated",
    invalidCredentials: "Invalid email or password (min 6 characters)",
    dashboardMessage: "Message from the Chief Executive",
    recentCompanyNews: "Recent company news",
    todaysMeetings: "Today's meetings",
    todaysAnnouncements: "Today's announcements",
    upcomingHolidays: "Upcoming holidays",
    featuredCrew: "Featured people",
    quickActions: "Quick actions",
    viewAll: "View all",
    organizationalStructure: "Organisational structure",
    departmentDirectory: "Department Directory",
    departmentsDescription: "Every department with its head, headcount, active projects, resources and its own notice board.",
    department: "Department",
    departmentHead: "Department head",
    headcount: "Headcount",
    currentProjects: "Current projects",
    resources: "Resources",
    departmentNoticeBoard: "Department notice board",
    employeeDirectory: "Employee Directory",
    employeesDescription: "Search the entire team by name, role, skill, location or availability.",
    searchByNameRole: "Search by name, role, skill or city…",
    all: "All",
    inOffice: "In office",
    remote: "Remote",
    inMeeting: "In meeting",
    onLeave: "On leave",
    viewProfile: "View profile",
    skills: "Skills",
    crewVoice: "Team voice",
    feedbackDescription: "Suggestions, anonymous reports, live polls and satisfaction ratings.",
    shareFeedback: "Share feedback",
    anonymous: "Anonymous",
    identified: "Identified",
    submitFeedback: "Submit feedback",
    writeFeedbackFirst: "Write your feedback first",
    thankYouFeedback: "Thank you — your feedback was recorded",
    livePolls: "Live polls",
    voteRecorded: "Vote recorded",
    recentSubmissions: "Recent submissions",
    noFeedbackYet: "No feedback yet — be the first.",
    peopleOperations: "People operations",
    leavePortal: "Leave Portal",
    leaveDescription: "Request leave, track manager approval and monitor your remaining balance.",
    newLeaveRequest: "New leave request",
    requestTimeline: "Request timeline",
    startDate: "Start date",
    endDate: "End date",
    reasonOptional: "Reason (optional)",
    submitRequest: "Submit request",
    selectStartEndDates: "Select start and end dates",
    leaveRequestSubmitted: "Leave request submitted to your manager",
    decisionRecorded: "Decision recorded",
    newsOverline: "Newsroom",
    companyNews: "Company News",
    newsDescription: "Milestones, rollouts, campuses and people — the running record of Novaterra Industries.",
    readStory: "Read story",
    companyMilestones: "Company milestones",
    mediaGallery: "Media gallery",
    noticesNetwork: "Digital billboard network",
    importantNotices: "Important Notices",
    noticesDescription: "Broadcast across every campus display, mobile device and workstation. Emergency notices pulse until acknowledged.",
    acknowledge: "Acknowledge",
    crewProtection: "People protection",
    safetyCentre: "Safety Centre",
    safetyDescription: "SOS and POSH are always one click away from every page. This is the escalation workflow behind those buttons.",
    sosEmergency: "SOS — Emergency",
    poshConfidentialReporting: "POSH — Confidential reporting",
    emergencyDescription: "Medical, fire, security or personal danger. Routes to the Global Security Desk and dispatches the nearest campus warden with your shared location.",
    poshDescription: "Harassment, discrimination or misconduct. Delivered only to the POSH committee chair, encrypted, with the option to remain fully anonymous.",
    escalationWorkflow: "Escalation workflow",
    reportRaised: "Report raised",
    dutyOfficerAck: "Duty officer ack",
    wardenDispatch: "Warden dispatch",
    incidentCommand: "Incident command",
    writtenClosure: "Written closure",
    reportLogRedacted: "Report log (redacted)",
    emergencyContacts: "Emergency contacts",
    noReportsFiled: "No reports filed. Use the floating buttons to test the workflow.",
    loadingLog: "Loading log…",
    emergencyEscalation: "Emergency escalation",
    immediateAssistance: "Immediate assistance",
    reportHarassmentOrMisconduct: "Report harassment or misconduct",
    encryptedToChair: "Encrypted and delivered only to the POSH committee chair. Response within 24 hours.",
    shareLocation: "Share location",
    pleaseDescribeSituation: "Please describe the situation before escalating.",
    escalating: "Escalating…",
    escalateNow: "Escalate now",
    submitReport: "Submit report",
    globalSecurityDeskNotified: "SOS escalated. Global Security Desk notified — stay on this screen.",
    poshReportFiled: "POSH report filed confidentially with the committee chair.",
    escalationFailed: "Escalation failed. Call the Global Security Desk on +354 511 0999.",
    
    announcementsOverline: "Company-wide announcements",
    announcementsTitle: "Announcements",
    announcementsDescription: "Every broadcast reaching the full team, with priority levels, attachments, reactions, comments and read receipts.",
    newAnnouncement: "New announcement",
    headlinePlaceholder: "Headline",
    announcementBodyPlaceholder: "Body of the announcement…",
    titleAndBodyRequired: "Title and body required",
    broadcast: "Broadcast",
    commentPosted: "Comment posted",
    announcementBroadcastSuccess: "Announcement broadcast company-wide",
    noAnnouncementsMatch: "No announcements match this filter.",
    comments: "comments",
    read: "read",
    addCommentPlaceholder: "Add a comment…",
    writeSomethingFirst: "Write something first",
    post: "Post",

    // Meeting Platform
    startMeeting: "Start Meeting",
    endCall: "End Call",
    mic: "Microphone",
    video: "Camera",
    screenShare: "Share Screen",
    participants: "Participants",
  },
  "English (US)": {
    command: "Command",
    communications: "Communications",
    organization: "Organization",
    workspace: "Workspace",
    dashboard: "Dashboard",
    ceo: "CEO Messages",
    announcements: "Announcements",
    notices: "Notices",
    news: "News",
    employees: "Employees",
    departments: "Departments",
    meetings: "Meeting Platform",
    settings: "Settings",
    safety: "Safety",
    leave: "Leave",
    feedback: "Feedback",
    calendar: "Calendar",
    
    searchPlaceholder: "Search people, docs, projects…",
    notifications: "Notifications",
    signOut: "Sign Out",
    welcome: "Welcome",
    logout: "Logout",
    pinnedAddress: "Pinned address",
    ceoDescription: "Full-length addresses, quarterly candour sessions and the leadership timeline of Novaterra Industries.",
    
    appearance: "Appearance",
    language: "Language & region",
    darkMode: "Deep obsidian, starfield active",
    lightMode: "Brushed titanium, daylight palette",
    interfaceLanguage: "Interface language set to",
    timezone: "Time zone follows your campus: America/New_York (EST).",
    companyAnnouncements: "Company announcements",
    companyAnnouncementsHint: "Critical broadcasts always deliver.",
    meetingReminders: "Meeting reminders",
    meetingRemindersHint: "10 minutes before start.",
    leaveDecisions: "Leave decisions",
    weeklyDigest: "Weekly digest",
    reduceMotion: "Reduce motion",
    reduceMotionHint: "Disables parallax and starfield drift.",
    highContrast: "High contrast",
    largerText: "Larger text",
    accessibility: "Accessibility",
    crewPreferences: "Team preferences",
    settingsDescription: "Theme, language, notifications, accessibility, profile and security controls.",
    profile: "Profile",
    security: "Security",
    displayName: "Display name",
    workEmail: "Work email",
    desk: "Desk",
    deskLocation: "Novaterra · Remote",
    digitalCampusCredential: "Digital campus credential",
    digitalCampusCredentialStatus: "Provisioned · expires 2027",
    twoFactorAuthentication: "Two-factor authentication",
    twoFactorAuthenticationStatus: "Hardware key · active",
    activeSessions: "Active sessions",
    activeSessionsStatus: "3 devices",
    cameraOff: "Camera off",
    toggleMic: "Toggle mic",
    toggleCamera: "Toggle camera",
    backgroundBlur: "Background blur",
    micOffMessage: "Microphone muted",
    micOnMessage: "Microphone unmuted",
    cameraOffMessage: "Camera turned off",
    cameraOnMessage: "Camera turned on",
    joinedMeeting: "Joined Q3 Company All-Hands",
    enterMeetingRoom: "Enter meeting room",
    meetingPlatform: "Meeting platform",
    missionControlLobby: "Collaboration Hub",
    meetingLobbyDescription: "Check your devices, then enter the room. Rooms are ephemeral and encrypted end to end.",
    endToEndEncrypted: "End-to-end encrypted",
    autoTranscriptionOn: "Auto-transcription on",
    latency: "Latency 18 ms",
    todayRooms: "Today's rooms",
    liveSession: "Live · Q3 Company All-Hands",
    missionControl: "Collaboration Hub",
    chat: "Chat",
    people: "People",
    board: "Board",
    notes: "Notes",
    shareScreen: "Share screen",
    screenShareStopped: "Screen share stopped",
    screenShareStarted: "Screen share started",
    raiseHand: "Raise hand",
    handRaised: "Hand raised",
    handLowered: "Hand lowered",
    record: "Record",
    leftMeeting: "You left the meeting",
    sendMessage: "Send message",
    signIn: "Sign In",
    welcomeBack: "Welcome back",
    enterCredentials: "Enter your credentials to access the company workspace",
    email: "Email",
    emailPlaceholder: "name@novaterra.io",
    password: "Password",
    passwordPlaceholder: "••••••••",
    authenticating: "Authenticating…",
    demoLoginHelp: "Demo: Use any email and password (6+ chars)",
    meetingNotes: "Meeting notes",
    minutesSaved: "Minutes saved to Team Calendar",
    publishMinutes: "Publish minutes",
    messageTheRoom: "Message the room…",
    saveProfile: "Save profile",
    profileUpdated: "Profile updated",
    
    startMeeting: "Start Meeting",
    endCall: "End Call",
    mic: "Microphone",
    video: "Camera",
    screenShare: "Share Screen",
    participants: "Participants",
  },
  "日本語": {
    command: "コマンド",
    communications: "コミュニケーション",
    organization: "組織",
    workspace: "ワークスペース",
    dashboard: "ダッシュボード",
    ceo: "CEO メッセージ",
    announcements: "お知らせ",
    notices: "告知",
    news: "ニュース",
    employees: "従業員",
    departments: "部門",
    meetings: "ミーティング",
    settings: "設定",
    safety: "安全",
    leave: "休暇",
    feedback: "フィードバック",
    calendar: "カレンダー",
    
    searchPlaceholder: "人、ドキュメント、プロジェクトを検索…",
    notifications: "通知",
    signOut: "サインアウト",
    welcome: "ようこそ",
    logout: "ログアウト",
    
    appearance: "外観",
    language: "言語と地域",
    darkMode: "深いオブシディアン、星野原始",
    lightMode: "ブラッシュ チタニウム、昼間パレット",
    interfaceLanguage: "インターフェース言語が",
    timezone: "タイムゾーン: Asia/Tokyo (JST)。",
    companyAnnouncements: "会社のお知らせ",
    companyAnnouncementsHint: "重要な放送は常に配信されます。",
    meetingReminders: "ミーティング リマインダー",
    meetingRemindersHint: "開始の10分前です。",
    leaveDecisions: "休暇の決定",
    weeklyDigest: "週間ダイジェスト",
    reduceMotion: "モーション削減",
    reduceMotionHint: "視差効果と星野のドリフトを無効にします。",
    highContrast: "高コントラスト",
    largerText: "大きなテキスト",
    accessibility: "アクセシビリティ",
    crewPreferences: "チーム設定",
    settingsDescription: "テーマ、言語、通知、アクセシビリティ、プロフィール、セキュリティ設定。",
    profile: "プロフィール",
    security: "セキュリティ",
    displayName: "表示名",
    workEmail: "勤務用メール",
    desk: "デスク",
    deskLocation: "Novaterra · リモート",
    digitalCampusCredential: "デジタルキャンパス認証",
    digitalCampusCredentialStatus: "発行済み · 2027年まで有効",
    twoFactorAuthentication: "二段階認証",
    twoFactorAuthenticationStatus: "ハードウェアキー · 有効",
    activeSessions: "アクティブセッション",
    activeSessionsStatus: "3台のデバイス",
    cameraOff: "カメラオフ",
    toggleMic: "マイク切替",
    toggleCamera: "カメラ切替",
    backgroundBlur: "背景ぼかし",
    micOffMessage: "マイクがミュートになりました",
    micOnMessage: "マイクのミュートが解除されました",
    cameraOffMessage: "カメラがオフになりました",
    cameraOnMessage: "カメラがオンになりました",
    joinedMeeting: "Q3 会社全体会議に参加しました",
    enterMeetingRoom: "ミーティングルームに入る",
    meetingPlatform: "ミーティングプラットフォーム",
    missionControlLobby: "コラボレーション ハブ",
    meetingLobbyDescription: "デバイスを確認してからルームに入ります。ルームは短命でエンドツーエンド暗号化されています。",
    endToEndEncrypted: "エンドツーエンド暗号化済み",
    autoTranscriptionOn: "自動文字起こしオン",
    latency: "レイテンシ 18 ms",
    todayRooms: "本日のルーム",
    liveSession: "ライブ · Q3 会社全体会議",
    missionControl: "コラボレーション ハブ",
    chat: "チャット",
    people: "参加者",
    board: "ボード",
    notes: "ノート",
    shareScreen: "画面共有",
    screenShareStopped: "画面共有を停止しました",
    screenShareStarted: "画面共有を開始しました",
    raiseHand: "挙手",
    handRaised: "手を上げました",
    handLowered: "手を下げました",
    record: "録画",
    leftMeeting: "ミーティングを退出しました",
    sendMessage: "メッセージを送信",
    signIn: "サインイン",
    welcomeBack: "お帰りなさい",
    enterCredentials: "コマンドセンターにアクセスするには、資格情報を入力してください",
    email: "メール",
    emailPlaceholder: "name@novaterra.io",
    password: "パスワード",
    passwordPlaceholder: "••••••••",
    authenticating: "認証中…",
    demoLoginHelp: "デモ: 任意のメールと6文字以上のパスワードを使用できます",
    meetingNotes: "ミーティングノート",
    minutesSaved: "टीम कैलेंडर में मिनट्स सहेजे गए",
    publishMinutes: "मिनट्स प्रकाशित करें",
    messageTheRoom: "कक्ष को संदेश भेजें…",
    saveProfile: "プロフィールを保存",
    profileUpdated: "プロフィールが更新されました",
    invalidCredentials: "無効なメールアドレスまたはパスワードです（6文字以上）",

    announcementsOverline: "社内更新",
    announcementsTitle: "お知らせ",
    announcementsDescription: "優先度、添付ファイル、リアクション、コメント、既読確認を備えた全社員向けの更新です。",
    newAnnouncement: "新しいお知らせ",
    headlinePlaceholder: "見出し",
    announcementBodyPlaceholder: "送信内容…",
    titleAndBodyRequired: "タイトルと本文を入力してください",
    broadcast: "送信",
    commentPosted: "コメントが投稿されました",
    announcementBroadcastSuccess: "お知らせを全社配信しました",
    noAnnouncementsMatch: "このフィルターに一致するお知らせはありません。",
    comments: "コメント",
    read: "既読",
    addCommentPlaceholder: "コメントを追加…",
    writeSomethingFirst: "最初に何か書いてください",
    post: "投稿",

    startMeeting: "ミーティングを開始",
    endCall: "通話を終了",
    mic: "マイク",
    video: "カメラ",
    screenShare: "画面共有",
    participants: "参加者",
  },
  "Deutsch": {
    command: "Befehl",
    communications: "Kommunikation",
    organization: "Organisation",
    workspace: "Arbeitsbereich",
    dashboard: "Instrumententafel",
    ceo: "CEO-Nachrichten",
    announcements: "Ankündigungen",
    notices: "Mitteilungen",
    news: "Nachrichten",
    employees: "Mitarbeiter",
    departments: "Abteilungen",
    meetings: "Meetings",
    settings: "Einstellungen",
    safety: "Sicherheit",
    leave: "Urlaub",
    feedback: "Rückmeldung",
    calendar: "Kalender",
    
    searchPlaceholder: "Personen, Dokumente, Projekte durchsuchen…",
    notifications: "Benachrichtigungen",
    signOut: "Abmelden",
    welcome: "Willkommen",
    logout: "Abmelden",
    
    appearance: "Darstellung",
    language: "Sprache und Region",
    darkMode: "Tiefes Obsidian, Sternfeld aktiv",
    lightMode: "Gebürstetes Titan, Tageslicht-Palette",
    interfaceLanguage: "Schnittstellensprache auf",
    timezone: "Zeitzone: Europe/Berlin (CEST).",
    companyAnnouncements: "Unternehmensankündigungen",
    companyAnnouncementsHint: "Kritische Meldungen werden immer zugestellt.",
    meetingReminders: "Besprechungserinnerungen",
    meetingRemindersHint: "10 Minuten vor Beginn.",
    leaveDecisions: "Urlaubsentscheidungen",
    weeklyDigest: "Wöchentliche Zusammenfassung",
    reduceMotion: "Bewegung reduzieren",
    reduceMotionHint: "Verringert Parallax und Sternfeldbewegung.",
    highContrast: "Hoher Kontrast",
    largerText: "Größerer Text",
    accessibility: "Barrierefreiheit",
    crewPreferences: "Team-Einstellungen",
    settingsDescription: "Design, Sprache, Benachrichtigungen, Barrierefreiheit, Profil und Sicherheit.",
    profile: "Profil",
    security: "Sicherheit",
    displayName: "Anzeigename",
    workEmail: "Arbeits-E-Mail",
    desk: "Arbeitsplatz",
    deskLocation: "Novaterra · Remote",
    digitalCampusCredential: "Digitale Campus-Anmeldeinformationen",
    digitalCampusCredentialStatus: "Ausgestellt · läuft bis 2027",
    twoFactorAuthentication: "Zwei-Faktor-Authentifizierung",
    twoFactorAuthenticationStatus: "Hardware-Schlüssel · aktiv",
    activeSessions: "Aktive Sitzungen",
    activeSessionsStatus: "3 Geräte",
    cameraOff: "Kamera aus",
    toggleMic: "Mikrofon umschalten",
    toggleCamera: "Kamera umschalten",
    backgroundBlur: "Hintergrundunschärfe",
    micOffMessage: "Mikrofon stummgeschaltet",
    micOnMessage: "Mikrofon aktiviert",
    cameraOffMessage: "Kamera ausgeschaltet",
    cameraOnMessage: "Kamera eingeschaltet",
    joinedMeeting: "Dem Q3 Company All-Hands beigetreten",
    enterMeetingRoom: "Meetingraum betreten",
    meetingPlatform: "Meeting-Plattform",
    missionControlLobby: "Collaboration Hub",
    meetingLobbyDescription: "Überprüfe deine Geräte und betrete dann den Raum. Räume sind flüchtig und Ende-zu-Ende verschlüsselt.",
    endToEndEncrypted: "Ende-zu-Ende verschlüsselt",
    autoTranscriptionOn: "Automatische Transkription aktiv",
    latency: "Latenz 18 ms",
    todayRooms: "Heutige Räume",
    liveSession: "Live · Q3 Company All-Hands",
    missionControl: "Collaboration Hub",
    chat: "Chat",
    people: "Personen",
    board: "Board",
    notes: "Notizen",
    shareScreen: "Bildschirm freigeben",
    screenShareStopped: "Bildschirmfreigabe gestoppt",
    screenShareStarted: "Bildschirmfreigabe gestartet",
    raiseHand: "Hand heben",
    handRaised: "Hand gehoben",
    handLowered: "Hand gesenkt",
    record: "Aufzeichnen",
    leftMeeting: "Sie haben das Meeting verlassen",
    sendMessage: "Nachricht senden",
    signIn: "Anmelden",
    welcomeBack: "Willkommen zurück",
    enterCredentials: "Geben Sie Ihre Zugangsdaten ein, um auf den Unternehmensarbeitsbereich zuzugreifen",
    email: "E-Mail",
    emailPlaceholder: "name@novaterra.io",
    password: "Passwort",
    passwordPlaceholder: "••••••••",
    authenticating: "Authentifizierung…",
    demoLoginHelp: "Demo: Verwenden Sie eine beliebige E-Mail und ein Kennwort mit mindestens 6 Zeichen",
    meetingNotes: "Besprechungsnotizen",
    minutesSaved: "Minuten im Teamkalender gespeichert",
    publishMinutes: "Protokoll veröffentlichen",
    messageTheRoom: "Nachricht an den Raum…",
    saveProfile: "Profil speichern",
    profileUpdated: "Profil aktualisiert",
    
    startMeeting: "Besprechung starten",
    endCall: "Anruf beenden",
    mic: "Mikrofon",
    video: "Kamera",
    screenShare: "Bildschirm freigeben",
    participants: "Teilnehmer",
  },
  "Français": {
    command: "Commande",
    communications: "Communications",
    organization: "Organisation",
    workspace: "Espace de travail",
    dashboard: "Tableau de bord",
    ceo: "Messages du PDG",
    announcements: "Annonces",
    notices: "Avis",
    news: "Actualités",
    employees: "Employés",
    departments: "Départements",
    meetings: "Réunions",
    settings: "Paramètres",
    safety: "Sécurité",
    leave: "Congés",
    feedback: "Retour d'information",
    calendar: "Calendrier",
    
    searchPlaceholder: "Rechercher personnes, documents, projets…",
    notifications: "Notifications",
    signOut: "Se déconnecter",
    welcome: "Bienvenue",
    logout: "Déconnexion",
    
    appearance: "Apparence",
    language: "Langue et région",
    darkMode: "Obsidienne profonde, champ d'étoiles actif",
    lightMode: "Titane brossé, palette de jour",
    interfaceLanguage: "Langue de l'interface définie sur",
    timezone: "Fuseau horaire: Europe/Paris (CEST).",
    companyAnnouncements: "Annonces de l'entreprise",
    companyAnnouncementsHint: "Les diffusions critiques sont toujours livrées.",
    meetingReminders: "Rappels de réunion",
    meetingRemindersHint: "10 minutes avant le début.",
    leaveDecisions: "Décisions de congés",
    weeklyDigest: "Résumé hebdomadaire",
    reduceMotion: "Réduire le mouvement",
    reduceMotionHint: "Désactive le parallaxe et le mouvement du champ d'étoiles.",
    highContrast: "Contraste élevé",
    largerText: "Texte plus grand",
    accessibility: "Accessibilité",
    crewPreferences: "Préférences de l'équipe",
    settingsDescription: "Thème, langue, notifications, accessibilité, profil et sécurité.",
    profile: "Profil",
    security: "Sécurité",
    displayName: "Nom affiché",
    workEmail: "E-mail professionnel",
    desk: "Bureau",
    deskLocation: "Novaterra · À distance",
    digitalCampusCredential: "Identifiants du campus numérique",
    digitalCampusCredentialStatus: "Provisionné · expire en 2027",
    twoFactorAuthentication: "Authentification à deux facteurs",
    twoFactorAuthenticationStatus: "Clé matérielle · active",
    activeSessions: "Sessions actives",
    activeSessionsStatus: "3 appareils",
    cameraOff: "Caméra désactivée",
    toggleMic: "Basculer le micro",
    toggleCamera: "Basculer la caméra",
    backgroundBlur: "Flou d'arrière-plan",
    micOffMessage: "Microphone coupé",
    micOnMessage: "Microphone activé",
    cameraOffMessage: "Caméra désactivée",
    cameraOnMessage: "Caméra activée",
    joinedMeeting: "Rejoint la réunion Q3 Company All-Hands",
    enterMeetingRoom: "Entrer dans la salle de réunion",
    meetingPlatform: "Plateforme de réunion",
    missionControlLobby: "Centre de collaboration",
    meetingLobbyDescription: "Vérifiez vos appareils, puis entrez dans la salle. Les pièces sont éphémères et chiffrées de bout en bout.",
    endToEndEncrypted: "Chiffré de bout en bout",
    autoTranscriptionOn: "Transcription automatique activée",
    latency: "Latence 18 ms",
    todayRooms: "Salles du jour",
    liveSession: "En direct · Q3 Company All-Hands",
    missionControl: "Centre de collaboration",
    chat: "Chat",
    people: "Personnes",
    board: "Tableau",
    notes: "Notes",
    shareScreen: "Partager l'écran",
    screenShareStopped: "Partage d'écran arrêté",
    screenShareStarted: "Partage d'écran commencé",
    raiseHand: "Lever la main",
    handRaised: "Main levée",
    handLowered: "Main baissée",
    record: "Enregistrer",
    leftMeeting: "Vous avez quitté la réunion",
    sendMessage: "Envoyer le message",
    signIn: "Se connecter",
    welcomeBack: "Bon retour",
    enterCredentials: "Entrez vos identifiants pour accéder au centre de commandement",
    email: "E-mail",
    emailPlaceholder: "name@novaterra.io",
    password: "Mot de passe",
    passwordPlaceholder: "••••••••",
    authenticating: "Authentification…",
    demoLoginHelp: "Démo : utilisez n'importe quel e-mail et mot de passe (6+ caractères)",
    meetingNotes: "Notes de réunion",
    minutesSaved: "Minutes enregistrées dans le calendrier d'équipe",
    publishMinutes: "Publier le compte rendu",
    messageTheRoom: "Envoyer un message à la salle…",
    saveProfile: "Enregistrer le profil",
    profileUpdated: "Profil mis à jour",
    
    startMeeting: "Démarrer la réunion",
    endCall: "Terminer l'appel",
    mic: "Microphone",
    video: "Caméra",
    screenShare: "Partager l'écran",
    participants: "Participants",
  },
  "हिन्दी": {
    command: "कमांड",
    communications: "संचार",
    organization: "संगठन",
    workspace: "कार्यक्षेत्र",
    dashboard: "डैशबोर्ड",
    ceo: "सीईओ संदेश",
    announcements: "घोषणाएं",
    notices: "सूचनाएं",
    news: "समाचार",
    employees: "कर्मचारी",
    departments: "विभाग",
    meetings: "मीटिंगें",
    settings: "सेटिंग्स",
    safety: "सुरक्षा",
    leave: "छुट्टी",
    feedback: "प्रतिक्रिया",
    calendar: "कैलेंडर",
    
    searchPlaceholder: "लोग, दस्तावेज़, प्रोजेक्ट खोजें…",
    notifications: "सूचनाएं",
    signOut: "साइन आउट करें",
    welcome: "स्वागत है",
    logout: "लॉग आउट करें",
    
    appearance: "उपस्थिति",
    language: "भाषा और क्षेत्र",
    darkMode: "गहरा ओब्सिडियन, स्टारफील्ड सक्रिय",
    lightMode: "ब्रशड टाइटेनियम, दिनभर पैलेट",
    interfaceLanguage: "इंटरफ़ेस भाषा सेट करें",
    timezone: "समय क्षेत्र: Asia/Kolkata (IST)।",
    companyAnnouncements: "कंपनी की घोषणाएं",
    companyAnnouncementsHint: "महत्वपूर्ण प्रसारण हमेशा भेजा जाता है।",
    meetingReminders: "मीटिंग रिमाइंडर",
    meetingRemindersHint: "शुरू होने से 10 मिनट पहले।",
    leaveDecisions: "छुट्टी के निर्णय",
    weeklyDigest: "साप्ताहिक सारांश",
    reduceMotion: "गति कम करें",
    reduceMotionHint: "पैरेलैक्स और स्टारफील्ड ड्रिफ्ट को अक्षम करता है।",
    highContrast: "उच्च विपरीतता",
    largerText: "बड़ा पाठ",
    accessibility: "पहुँच",
    crewPreferences: "टीम प्राथमिकताएँ",
    settingsDescription: "थीम, भाषा, सूचना, सहजता, प्रोफ़ाइल और सुरक्षा नियंत्रण।",
    profile: "प्रोफ़ाइल",
    security: "सुरक्षा",
    displayName: "प्रदर्शन नाम",
    workEmail: "कार्य ईमेल",
    desk: "डेस्क",
    deskLocation: "Novaterra · रिमोट",
    digitalCampusCredential: "डिजिटल कैंपस क्रेडेंशियल",
    digitalCampusCredentialStatus: "प्रोविजन किया गया · 2027 तक मान्य",
    twoFactorAuthentication: "दो-कारक प्रमाणीकरण",
    twoFactorAuthenticationStatus: "हार्डवेयर कुंजी · सक्रिय",
    activeSessions: "सक्रिय सत्र",
    activeSessionsStatus: "3 डिवाइस",
    cameraOff: "कैमरा बंद",
    toggleMic: "माइक टॉगल करें",
    toggleCamera: "कैमरा टॉगल करें",
    backgroundBlur: "पृष्ठभूमि धुंधला",
    micOffMessage: "माइक्रोफोन म्यूट कर दिया गया है",
    micOnMessage: "माइक्रोफोन अनम्यूट हो गया है",
    cameraOffMessage: "कैमरा बंद कर दिया गया है",
    cameraOnMessage: "कैमरा चालू कर दिया गया है",
    joinedMeeting: "Q3 कंपनी ऑल-हैंड्स में शामिल हुए",
    enterMeetingRoom: "मीटिंग रूम में प्रवेश करें",
    meetingPlatform: "मीटिंग प्लेटफ़ॉर्म",
    missionControlLobby: "सहयोग केंद्र",
    meetingLobbyDescription: "अपने डिवाइस जांचें, फिर कमरे में प्रवेश करें। कमरे अल्पकालिक और एंड-टू-एंड एन्क्रिप्टेड हैं।",
    endToEndEncrypted: "एंड-टू-एंड एन्क्रिप्टेड",
    autoTranscriptionOn: "स्वचालित ट्रांसक्रिप्शन चालू है",
    latency: "लेटेंसी 18 ms",
    todayRooms: "आज के कमरे",
    liveSession: "लाइव · Q3 कंपनी ऑल-हैंड्स",
    missionControl: "सहयोग केंद्र",
    chat: "चैट",
    people: "लोग",
    board: "बोर्ड",
    notes: "नोट्स",
    shareScreen: "स्क्रीन साझा करें",
    screenShareStopped: "स्क्रीन साझा करना बंद किया गया",
    screenShareStarted: "स्क्रीन साझा करना शुरू किया गया",
    raiseHand: "हाथ उठाएं",
    handRaised: "हाथ उठा लिया",
    handLowered: "हाथ नीचे किया गया",
    record: "रिकॉर्ड",
    leftMeeting: "आप मीटिंग छोड़ चुके हैं",
    sendMessage: "संदेश भेजें",
    signIn: "साइन इन",
    welcomeBack: "वापसी पर स्वागत है",
    enterCredentials: "कंपनी वर्कस्पेस तक पहुंचने के लिए अपने क्रेडेंशियल दर्ज करें",
    email: "ईमेल",
    emailPlaceholder: "name@novaterra.io",
    password: "पासवर्ड",
    passwordPlaceholder: "••••••••",
    authenticating: "प्रमाणीकरण हो रहा है…",
    demoLoginHelp: "डेमो: कोई भी ईमेल और 6+ वर्ण पासवर्ड उपयोग करें",
    meetingNotes: "मीटिंग नोट्स",
    minutesSaved: "टीम कैलेंडर में मिनट्स सहेजे गए",
    publishMinutes: "मिनट्स प्रकाशित करें",
    messageTheRoom: "रूम को संदेश भेजें…",
    saveProfile: "प्रोफ़ाइल सहेजें",
    profileUpdated: "प्रोफ़ाइल अपडेट की गई",
    dashboardMessage: "मुख्य कार्यकारी से संदेश",
    recentCompanyNews: "हाल की कंपनी समाचार",
    todaysMeetings: "आज की मीटिंगें",
    todaysAnnouncements: "आज की घोषणाएं",
    upcomingHolidays: "आगामी छुट्टियाँ",
    featuredCrew: "मान्यता प्राप्त क्रू",
    quickActions: "त्वरित क्रियाएं",
    viewAll: "सभी देखें",
    organizationalStructure: "संगठनात्मक संरचना",
    departmentDirectory: "विभाग निर्देशिका",
    departmentsDescription: "प्रत्येक विभाग अपने प्रमुख, कर्मचारी संख्या, लाइव मिशन, संसाधन और अपना नोटिस बोर्ड दिखाता है।",
    department: "विभाग",
    departmentHead: "विभाग प्रमुख",
    headcount: "कर्मचारी संख्या",
    currentProjects: "चल रहे प्रोजेक्ट",
    resources: "संसाधन",
    departmentNoticeBoard: "विभाग नोटिस बोर्ड",
    employeeDirectory: "कर्मचारी निर्देशिका",
    employeesDescription: "पूरा क्रू नाम, भूमिका, कौशल, स्थान या उपलब्धता से खोजें।",
    searchByNameRole: "नाम, भूमिका, कौशल या शहर द्वारा खोजें…",
    all: "सभी",
    inOffice: "कार्यालय में",
    remote: "रिमोट",
    inMeeting: "मीटिंग में",
    onLeave: "छुट्टी पर",
    viewProfile: "प्रोफ़ाइल देखें",
    skills: "कौशल",
    crewVoice: "क्रू की आवाज़",
    feedbackDescription: "सुझाव, गुमनाम रिपोर्ट, लाइव पोल और संतुष्टि रेटिंग।",
    shareFeedback: "प्रतिक्रिया साझा करें",
    anonymous: "गुमनाम",
    identified: "पहचाना गया",
    submitFeedback: "प्रतिक्रिया सबमिट करें",
    writeFeedbackFirst: "पहले अपनी प्रतिक्रिया लिखें",
    thankYouFeedback: "धन्यवाद — आपकी प्रतिक्रिया रिकॉर्ड की गई।",
    livePolls: "लाइव पोल",
    voteRecorded: "वोट दर्ज किया गया",
    peopleOperations: "पीपल ऑपरेशन्स",
    leavePortal: "छुट्टी पोर्टल",
    leaveDescription: "छुट्टी का अनुरोध करें, प्रबंधक स्वीकृति ट्रैक करें और अपनी शेष शेष राशि देखें।",
    newLeaveRequest: "नए छुट्टी अनुरोध",
    requestTimeline: "अनुरोध समयरेखा",
    startDate: "आरंभ तिथि",
    endDate: "समाप्ति तिथि",
    reasonOptional: "कारण (वैकल्पिक)",
    submitRequest: "अनुरोध सबमिट करें",
    selectStartEndDates: "शुरू और समाप्ति तिथि चुनें",
    newsOverline: "न्यूज़रूम",
    companyNews: "कंपनी समाचार",
    newsDescription: "माइलस्टोन, प्रक्षेपण, कैंपस और क्रू — नोवाटेरा इंडस्ट्रीज़ का चल रहा रिकॉर्ड।",
    readStory: "कहानी पढ़ें",
    companyMilestones: "कंपनी माइलस्टोन",
    mediaGallery: "मीडिया गैलरी",
    noticesNetwork: "डिजिटल बिलबोर्ड नेटवर्क",
    importantNotices: "महत्वपूर्ण सूचनाएं",
    noticesDescription: "हर कैंपस डिस्प्ले, मोबाइल डिवाइस और वर्कस्टेशन पर प्रसारित करें। आपातकालीन सूचनाएं स्वीकार किए जाने तक पॉल करती हैं।",
    acknowledge: "स्वीकार करें",
    crewProtection: "क्रू सुरक्षा",
    safetyCentre: "सुरक्षा केंद्र",
    safetyDescription: "SOS और POSH प्रत्येक पेज से हमेशा एक क्लिक दूर हैं। यह उन बटनों के पीछे की जागरूकता वर्कफ़्लो है।",
    sosEmergency: "SOS — आपातकालीन",
    poshConfidentialReporting: "POSH — गोपनीय रिपोर्टिंग",
    emergencyDescription: "चिकित्सा, आग, सुरक्षा या व्यक्तिगत खतरा। यह ग्लोबल सुरक्षा डेस्क और निकटतम कैंपस वॉर्डन को आपकी साझा स्थिति के साथ रूट करता है।",
    poshDescription: "उत्पीड़न, भेदभाव या कदाचार। केवल POSH समिति अध्यक्ष को एन्क्रिप्टेड रूप से भेजा जाता है। पूर्ण गुमनामी का विकल्प।",
    escalationWorkflow: "जागरूकता वर्कफ़्लो",
    reportRaised: "रिपोर्ट दर्ज की गई",
    dutyOfficerAck: "ड्यूटी ऑफिसर स्वीकृति",
    wardenDispatch: "वार्डन प्रेषण",
    incidentCommand: "घटना कमान",
    writtenClosure: "लिखित समापन",
    reportLogRedacted: "रिपोर्ट लॉग (रेडैक्टेड)",
    emergencyContacts: "आपातकालीन संपर्क",
    noReportsFiled: "कोई रिपोर्ट दर्ज नहीं की गई। वर्कफ़्लो का परीक्षण करने के लिए फ़्लोटिंग बटन का उपयोग करें।",
    loadingLog: "लॉग लोड हो रहा है…",
    emergencyEscalation: "आपातकालीन जागरूकता",
    immediateAssistance: "तत्काल सहायता",
    reportHarassmentOrMisconduct: "उत्पीड़न या दुराचार की रिपोर्ट करें",
    encryptedToChair: "केवल POSH समिति अध्यक्ष को एन्क्रिप्टेड रूप से भेजा गया। 24 घंटे के भीतर प्रतिक्रिया।",
    shareLocation: "स्थान साझा करें",
    escalating: "जागरूक कर रहा है…",
    escalateNow: "अभी जागरूक करें",
    submitReport: "रिपोर्ट सबमिट करें",
    globalSecurityDeskNotified: "SOS जागरूक किया गया। ग्लोबल सुरक्षा डेस्क को सूचित किया गया — इस स्क्रीन पर रहें।",
    poshReportFiled: "POSH रिपोर्ट गोपनीय रूप से समिति अध्यक्ष को दर्ज की गई।",
    escalationFailed: "जागरूकता विफल हुई। ग्लोबल सुरक्षा डेस्क पर +354 511 0999 पर कॉल करें।",

    startMeeting: "मीटिंग शुरू करें",
    endCall: "कॉल समाप्त करें",
    mic: "माइक्रोफोन",
    video: "कैमरा",
    screenShare: "स्क्रीन साझा करें",
    participants: "प्रतिभागियों",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("syncsphere-language") || "English (UK)";
  });

  const handleSetLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem("syncsphere-language", lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);

export const useTranslation = () => {
  const { language, translations } = useLanguage();
  return translations[language] || translations["English (UK)"];
};
